[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
via_ir = true

[rpc_endpoints]
arbitrum = "https://arb1.arbitrum.io/rpc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
